task:
  name: build-macos-aarch64
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  stack_cache:
    folder: ~/.stack
    fingerprint_script:
      - grep -F resolver stack.yaml
  setup_script:
    - brew update
    - brew install --force-bottle haskell-stack
    - stack setup
  build_script:
    - stack --no-terminal --no-interleaved-output install --flag hprox:quic
  package_and_clean_script:
    - if [ -n "$CIRRUS_TAG" ]; then VER="$CIRRUS_TAG"; else VER="$(stack query locals hprox version)-$(git rev-parse --short HEAD)"; fi
    - tar czvf "hprox-$VER-darwin-aarch64.tar.gz" -C ~/.local/bin hprox
    - rm -rf "$(stack path --programs)"
  release_artifacts:
    path: ./hprox-*.tar.gz
