name:                hprox
version:             0.6.1
github:              "bjin/hprox"
license:             Apache-2.0
author:              "Bin Jin"
maintainer:          "bjin@ctrl-d.org"
copyright:           "2023 Bin Jin"

synopsis:            a lightweight HTTP proxy server, and more
category:            Web

description:
  Please see the README on GitHub at <https://github.com/bjin/hprox#readme>

extra-source-files:
- README.md
- Changelog.md

flags:
  static:
    description: Enable static build
    manual: true
    default: false
  quic:
    description: Enable QUIC (HTTP/3) support
    manual: true
    default: false

default-extensions:
- ImportQualifiedPost
- OverloadedStrings
- RecordWildCards

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
  - Network.HProx
  dependencies:
  - async >= 2.2
  - base >= 4.12 && < 5
  - base64-bytestring >= 1.1
  - binary >= 0.8
  - bytestring >= 0.10
  - case-insensitive >= 1.2
  - conduit >= 1.3
  - conduit-extra >= 1.3
  - crypton
  - data-default-class
  - dns >= 4.0
  - fast-logger >= 3.0
  - http-client >= 0.5
  - http-client-tls >= 0.3.4
  - http-reverse-proxy >= 0.6.0.2
  - http-types >= 0.12
  - http2 >= 4.0
  - optparse-applicative >= 0.14
  - random >= 1.2.1
  - text
  - tls >= 1.5
  - tls-session-manager >= 0.0.4
  - unordered-containers
  - wai >= 3.2.2
  - wai-extra >= 3.0
  - warp >= 3.2.8
  - warp-tls >= 3.2.12
  when:
  - condition: flag(quic)
    cpp-options: -DQUIC_ENABLED
    dependencies:
    - http3 >= 0.0.3
    - quic >= 0.1.15
    - warp-quic
    when:
    - condition: os(linux)
      cpp-options: -DDROP_ALL_CAPS_EXCEPT_BIND
      c-sources: cbits/setcap.c
      dependencies:
      - directory >= 1.2.5.0
  - condition: '!os(windows)'
    cpp-options: -DOS_UNIX
    dependencies:
    - unix

executables:
  hprox:
    main: Main.hs
    source-dirs:
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    when:
    - condition: flag(static)
      ghc-options: -optl-static
    dependencies:
    - base
    - bytestring
    - hprox
    - http-types
    - wai
