name:                hprox
version:             0.3.0
github:              "bjin/hprox"
license:             Apache-2.0
author:              "Bin Jin"
maintainer:          "bjin@ctrl-d.org"
copyright:           "2023 Bin Jin"

synopsis:            a lightweight HTTP proxy server, and more
category:            Web

description:
  Please see the README on GitHub at <https://github.com/bjin/hprox#readme>

extra-source-files:
- README.md
- Changelog.md

dependencies:
- async >= 2.2
- base >= 4.12 && < 5
- base64-bytestring >= 1.1
- binary >= 0.8
- bytestring >= 0.10
- case-insensitive >= 1.2
- conduit >= 1.3
- conduit-extra >= 1.3
- dns >= 4.0
- http-client >= 0.5
- http-client-tls >= 0.3.4
- http-reverse-proxy >= 0.4.0
- http-types >= 0.12
- optparse-applicative >= 0.14
- tls >= 1.5
- unix >= 2.7
- wai >= 3.2.2
- wai-extra >= 3.0
- warp >= 3.2.8
- warp-tls >= 3.2.5
- random

flags:
  static:
    description: Enable static build
    manual: true
    default: false

default-extensions:
- ImportQualifiedPost
- OverloadedStrings
- RecordWildCards

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Network.HProx

executables:
  hprox:
    main:                Main.hs
    source-dirs:
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    when:
    - condition: flag(static)
      ghc-options: -optl-static
    dependencies:
    - hprox
