resolver: lts-22.24
packages:
- '.'
extra-deps:
- github: bjin/wai
  commit: warp-3.4.1-patched
  subdirs:
  - warp
- github: bjin/http-reverse-proxy
  commit: fix-encoding
- auto-update-0.2.0
- crypto-token-0.1.1
- http-semantics-0.0.1
- http2-5.2.2
- http3-0.0.12
- network-control-0.1.0
- network-udp-0.0.0
- quic-0.1.20
- sockaddr-0.0.1
- time-manager-0.1.0
- tls-2.0.6
- tls-session-manager-0.0.5
- warp-quic-0.0.0
drop-packages:
- cryptonite
flags:
  hprox:
    quic: true
apply-ghc-options: everything
nix:
  packages:
  - libcap
  - zlib
