resolver: lts-13.20
packages:
- '.'
extra-deps:
- github: vincenthz/hs-tls
  commit: 35317d8c2b920c33ca99ac0dd7197c7b8988da62
  subdirs:
  - core
- github: yesodweb/wai
  commit: fce402961a03fec97bd2eb2ea5d25b5162f8cd43
  subdirs:
  - warp-tls
- github: bjin/wai
  commit: http2-scheme
  subdirs:
  - warp
flags: {}
extra-package-dbs: []
