resolver: lts-22.7
packages:
- '.'
allow-newer: true
allow-newer-deps:
- warp-tls
extra-deps:
- github: bjin/wai
  commit: warp-3.4.0-patched
  subdirs:
  - warp
- crypto-token-0.1.0
- http2-5.1.0
- http3-0.0.8
- network-udp-0.0.0
- quic-0.1.15
- sockaddr-0.0.1
- tls-1.9.0
- warp-quic-0.0.0
drop-packages:
- cryptonite
flags:
  hprox:
    quic: true
apply-ghc-options: everything
nix:
  packages:
  - libcap
  - zlib
