resolver: lts-22.41
packages:
- '.'
extra-deps:
- github: bjin/wai
  commit: warp-3.4.4-patched
  subdirs:
  - warp
- auto-update-0.2.2
- crypto-token-0.1.2
- crypton-connection-0.4.2
- http-semantics-0.3.0
- http2-5.3.5
- http3-0.0.19
- network-control-0.1.3
- network-udp-0.0.0
- quic-0.2.4
- sockaddr-0.0.1
- time-manager-0.1.1
- tls-2.1.4
- tls-session-manager-0.0.7
- warp-quic-0.0.2
- warp-tls-3.4.11
drop-packages:
- cryptonite
flags:
  hprox:
    quic: true
apply-ghc-options: everything
nix:
  packages:
  - libcap
  - zlib
