resolver: lts-22.16
packages:
- '.'
extra-deps:
- github: bjin/wai
  commit: warp-3.4.0-patched
  subdirs:
  - warp
- crypto-token-0.1.1
- http2-5.1.4
- http3-0.0.10
- network-control-0.1.0
- network-udp-0.0.0
- quic-0.1.20
- sockaddr-0.0.1
- tls-2.0.2
- tls-session-manager-0.0.5
- warp-quic-0.0.0
drop-packages:
- cryptonite
flags:
  hprox:
    quic: true
apply-ghc-options: everything
nix:
  packages:
  - libcap
  - zlib
