resolver: nightly-2023-06-04
packages:
- '.'
extra-deps:
- github: bjin/wai
  commit: warp-3.3.25-patched
  subdirs:
  - warp
- crypto-token-0.0.1
- http3-0.0.3
- network-udp-0.0.0
- quic-0.1.1
- sockaddr-0.0.1
- warp-quic-0.0.0
flags:
  hprox:
    quic: true
apply-ghc-options: everything
