resolver: lts-22.37
packages:
- '.'
extra-deps:
- github: bjin/wai
  commit: warp-3.4.2-patched
  subdirs:
  - warp
- auto-update-0.2.1
- crypto-token-0.1.1
- crypton-connection-0.4.1
- http-semantics-0.2.1
- http2-5.3.4
- http3-0.0.18
- network-control-0.1.3
- network-udp-0.0.0
- quic-0.2.2
- sockaddr-0.0.1
- time-manager-0.1.0
- tls-2.1.0
- tls-session-manager-0.0.6
- warp-quic-0.0.1
- warp-tls-3.4.7
drop-packages:
- cryptonite
flags:
  hprox:
    quic: true
apply-ghc-options: everything
nix:
  packages:
  - libcap
  - zlib
