resolver: lts-22.6
packages:
- '.'
extra-deps:
- github: bjin/wai
  commit: warp-3.3.31-patched
  subdirs:
  - warp
- crypto-token-0.1.0
- http3-0.0.7
- network-udp-0.0.0
- quic-0.1.15
- sockaddr-0.0.1
- tls-1.9.0
- warp-quic-0.0.0
drop-packages:
- cryptonite
flags:
  hprox:
    quic: true
apply-ghc-options: everything
nix:
  packages:
  - zlib
